name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  Awesome_Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - run: npx awesome-lint